const Fonts = {
  fontawsome: {
    versions:{
      '4': {
        'change-map': "fa fa-map-signs",
        map: "fa fa-map-o",
        file: "fa fa-file-code-o",
        marker: "fa fa-map-marker",
        relation: "fa fa-sitemap",
        tools: "fa fa-gears",
        tool: "fa fa-gear",
        search: "fa fa-search",
        print: "fa fa-print",
        info: "fa fa-info",
        'info-circle': "fa fa-info-circle",
        globe: "fa fa-globe",
        mail: "fa fa-envelope-o",
        mobile: "fa fa-mobile",
        fax: "fa fa-fax",
        user: "fa fa-user",
        bars: "fa fa-bars",
        uncheck: "fa fa-square-o",
        check: "fa fa-check-square-o",
        filluncheck: "fa fa-square",
        table: "fa fa-table",
        trash: "fa fa-trash",
        'arrow-up': "fa fa-chevron-up",
        'arrow-down': "fa fa-chevron-down",
        'arrow-left': "fa fa-chevron-left",
        'arrow-right': "fa fa-chevron-right",
        'angle-up': "fa fa-angle-up",
        'angle-down': "fa fa-angle-down",
        'angle-left': "fa fa-angle-left",
        'angle-right': "fa fa-angle-right",
        'caret-up': "fa fa-caret-up",
        'caret-down': "fa fa-caret-down",
        'caret-left': "fa fa-caret-left",
        'caret-right': "fa fa-caret-right",
        'empty-circle': "fa fa-circle-o",
        'cloud-upload': "fa fa-cloud-upload",
        spinner: "fa fa-spinner",
        minus: "fa fa-minus",
        plus: "fa fa-plus",
        grid: "fa fa-th",
        home: "fa fa-home",
        folder: "fa fa-folder",
        'sign-out': "fa fa-sign-out",
        close: "fa fa-times",
        time: "fa fa-clock-o",
        calendar: "fa fa-calendar",
        list: "fa fa-list-alt",
        link: "fa fa-link",
        eye: "fa fa-eye",
        'eye-close': "fa fa-eye-slash"
      },
      '5': {
        'change-map': "fas fa-map-sign",
        map: "fas fa-map",
        file: "fas fa-file-code",
        marker: "fas fa-map-marker-alt",
        relation: "fas fa-sitemap",
        tools: "fas fa-cogs",
        tool: "fas fa-cog",
        search: "fas fa-search",
        print: "fas fa-print",
        info: "fas fa-info",
        'info-circle': "fas fa-info-circle",
        globe: "fas fa-globe",
        mail: "fas fa-envelope",
        mobile: "fas fa-mobile",
        fax: "fas fa-fax",
        user: "fas fa-user",
        bars: "fas fa-bars",
        uncheck: "far fa-square",
        check: "far fa-check-square",
        filluncheck: "fas fa-square",
        table: "fas fa-table",
        trash: "fas fa-trash",
        'arrow-up': "fas fa-chevron-up",
        'arrow-down': "fas fa-chevron-down",
        'arrow-left': "fas fa-chevron-left",
        'arrow-right': "fas fa-chevron-right",
        'caret-up': "fas fa-caret-up",
        'caret-down': "fas fa-caret-down",
        'caret-left': "fas fa-caret-left",
        'caret-right': "fas fa-caret-right",
        'empty-circle': "far fa-circle",
        'cloud-upload': "fas fa-cloud-upload-alt",
        spinner: "fas fa-spinner",
        minus: "fas fa-minus",
        plus: "fas fa-plus",
        grid: "fas fa-th",
        home: "fas fa-home",
        folder: "fas fa-folder",
        'sign-out': "fas fa-sign-out-alt",
        close: "fas fa-times",
        time: "far fa-time",
        calendar: "fas fa-calendar-alt",
        list: "fas fa-list-alt",
        link: "fas fa-link",
        eye: "far fa-eye",
        'eye-close': "far fa-eye-slash"
      }
    }
  }
};

module.exports = Fonts;
